Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|
    aws.keypair_name = "aws-vm01"
    aws.security_groups = [ 'Vagrant' ] 
    aws.region = "us-east-1"
    aws.ami = "ami-7747d01e"
    aws.instance_type = "t2.micro"

    override.ssh.username = "centos"
    override.ssh.private_key_path = "/home/devadmin/vms/keys/aws-vm01.pem"
  end
end
